-- begin WFSTPDEMO_TICKET
alter table WFSTPDEMO_TICKET add constraint FK_WFSTPDEMO_TICKET_ON_WORKFLOW foreign key (WORKFLOW_ID) references WFSTP_WORKFLOW(ID)^
create index IDX_WFSTPDEMO_TICKET_ON_WORKFLOW on WFSTPDEMO_TICKET (WORKFLOW_ID)^
-- end WFSTPDEMO_TICKET
